### ISSUE TITLE
Sanity: Translation Plugin

### ISSUE THREAD

**Issue by bryceknz** [bryceknz/sanity-translations-experiment#32]
# Description

Once we have the basic building blocks in place, it would be good if we were able to package this up into a Sanity plugin.

# Acceptance criteria

- [x] Investigate the viability of wrapping the MVP functionality into a Sanity plugin.
- [x] Present findings to team in a scheduled meeting.

**Comment by umxr** [comment]
Brain Dump 09/10/2023

Initial thoughts...Yes. We can quite easily create a plugin for this. Lets run through an example workflow of how a content manager would create a new document with and without translations. 

**Questions**
- Would we ship the sanity translations plugin with our plugin, or mention that its a dependancy of this plugin and it must be installed otherwise our plugin will not function as expected
- Should we allow users manage the list of languages they want to support, i know the initial idea we had was support translations for a list of defined languages, but then default to en-US if a locale is not supported. Do we still want to do this? If we do then we need to think of a way to allow users to select which locales/languages they want to support. Users could manage this list in the custom tool.

**Tool**
For MVP, the custom tool wouldnt really do much. We'd need a way to allow users to add their own OpenAI api keys, so having this in the custom tool would make sense. A basic `string` field with some validation would suffice. Thinking behind is just so that were not footing the bill for millions of users (gotta think big right... 😄)

**Document Editing**
Because were leveraging the official sanity plugin, users will already have extra document actions for creating/editing documents. a `Generate Translation` action will also be present for documents once the plugin has been setup. From a CMS perspective, Once clicked the user would be asked which language they want to trigger a translation for and if they are 100% sure they want to do it. This will then fire off a request to the server passing in all relevant information. The server "should" then handle the rest. We should think of a way to notify the user within the studio that a translation is currently in process. Im not a complete fan of this idea but we could do something similar to PUMA, its very much overkill but i did work

**Comment by umxr** [comment]
Summary 11/10/2023

After reviewing the points above and mentioning new ones, Weve come to the conclusion it is entirely possible to ship this idea to the world as a Sanity plugin, however we would need to make quite a few changes to the current setup.

**Sanity**
- Updating desk structure
- removing dependancy on [sanity document internationalization plugin](https://www.sanity.io/plugins/document-internationalization)
- update `Post` schema to support Locale fields eg LocaleString, LocalePortableText (puma inspired)
- Implement #37 

**API**
- Implement #11 
- refactor `afterHandle` event to support new method of translations

cc @umxr @dtaylorbrown
